# Generated by Django 5.1.3 on 2024-11-29 17:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client_order_id', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(blank=True, choices=[('received', 'received'), ('placed', 'placed'), ('canceled', 'canceled'), ('filled', 'filled')], default='received', max_length=15, null=True)),
                ('side', models.CharField(blank=True, choices=[('buy', 'buy'), ('sell', 'sell')], default='buy', max_length=5, null=True)),
                ('type', models.CharField(blank=True, choices=[('limit', 'limit')], default='limit', max_length=20, null=True)),
                ('time_in_force', models.CharField(blank=True, choices=[('gtc', 'gtc'), ('iok', 'iok')], default='gtc', max_length=5, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('filled_quantity', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('quote_quantity', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('filled_quote_quantity', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('locked_amount', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('post_only', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('symbol', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('lot_size', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('tick_size', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('priority', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('paid_token_amount', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('paid_token_rebate', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('received_token_amount', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('received_token_fee', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('is_maker', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
