# Generated by Django 5.1.3 on 2024-11-30 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='paid_token_amount',
            new_name='paid_amount',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='paid_token_rebate',
            new_name='paid_rebate',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='received_token_amount',
            new_name='received_amount',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='received_token_fee',
            new_name='received_fee',
        ),
    ]
