# Generated by Django 5.1.3 on 2024-11-30 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0003_rename_paid_token_amount_trade_paid_amount_and_more'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='paid_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spot_paid', to='wallet.token'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='received_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spot_received', to='wallet.token'),
        ),
    ]
