# Generated by Django 5.1.3 on 2024-12-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0004_alter_trade_paid_token_alter_trade_received_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, choices=[('limit', 'limit'), ('market', 'market')], default='limit', max_length=20, null=True),
        ),
    ]
