# Generated by Django 5.1.3 on 2025-01-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0006_symbol_account'),
        ('wallet', '0002_token_account_token_supply_alter_token_priority'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='symbol',
            unique_together={('base', 'quote')},
        ),
    ]
