# Generated by Django 5.1.3 on 2025-01-18 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aaa', '0001_initial'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aaa.account'),
        ),
        migrations.AddField(
            model_name='token',
            name='supply',
            field=models.PositiveBigIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='priority',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
