# Generated by Django 5.1.3 on 2025-01-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_token_account_token_supply_alter_token_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='is_withdrawable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='is_transferable',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
