# Generated by Django 5.1.3 on 2024-11-30 15:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aaa', '0001_initial'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('symbol', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('base', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('margin_amount', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('lot_size', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('max_size', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('max_leverage', models.IntegerField(blank=True, default=10, null=True)),
                ('priority', models.IntegerField(blank=True, default=0, null=True)),
                ('tick_size', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('margin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perp_margin', to='wallet.token')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prep_quote', to='wallet.token')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='PerpetualWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aaa.account')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wallet.token')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client_order_id', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(blank=True, choices=[('received', 'received'), ('placed', 'placed'), ('canceled', 'canceled'), ('filled', 'filled')], default='received', max_length=15, null=True)),
                ('direction', models.CharField(blank=True, choices=[('long', 'long'), ('short', 'short')], default='long', max_length=5, null=True)),
                ('type', models.CharField(blank=True, choices=[('limit', 'limit')], default='limit', max_length=20, null=True)),
                ('leverage', models.IntegerField(blank=True, default=10, null=True)),
                ('margin', models.CharField(blank=True, choices=[('isolated', 'isolated')], default='isolated', max_length=20, null=True)),
                ('mode', models.CharField(blank=True, choices=[('oneway', 'oneway')], default='oneway', max_length=20, null=True)),
                ('time_in_force', models.CharField(blank=True, choices=[('gtc', 'gtc'), ('iok', 'iok')], default='gtc', max_length=5, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('size', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('filled_size', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('quote_quantity', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('filled_quote_quantity', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('locked_amount', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('locked_fee', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('post_only', models.BooleanField(blank=True, default=False, null=True)),
                ('close_only', models.BooleanField(blank=True, default=False, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perpetual_order', to='aaa.account')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='perpetual.contract')),
                ('locked_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='perpetual.perpetualwallet')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=15, null=True)),
                ('direction', models.CharField(blank=True, choices=[('long', 'long'), ('short', 'short')], default='long', max_length=5, null=True)),
                ('margin', models.CharField(blank=True, choices=[('isolated', 'isolated')], default='isolated', max_length=20, null=True)),
                ('mode', models.CharField(blank=True, choices=[('oneway', 'oneway')], default='oneway', max_length=20, null=True)),
                ('leverage', models.IntegerField(blank=True, default=10, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('entry_price', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('exit_price', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aaa.account')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='perpetual.contract')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('margin', models.CharField(blank=True, choices=[('isolated', 'isolated')], default='isolated', max_length=20, null=True)),
                ('mode', models.CharField(blank=True, choices=[('oneway', 'oneway')], default='oneway', max_length=20, null=True)),
                ('leverage', models.IntegerField(blank=True, default=10, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aaa.account')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='perpetual.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('size', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('paid_rebate', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('paid_fee', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('is_maker', models.BooleanField(blank=True, default=False, null=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='perpetual.contract')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='perpetual.order')),
                ('paid_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perp_paid', to='wallet.token')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.token')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perpetual.trade')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='perpetualwallet',
            index=models.Index(fields=['account', 'token'], name='perpetual_p_account_6cd733_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='perpetualwallet',
            unique_together={('account', 'token')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['direction', 'price'], name='perpetual_o_directi_7e216d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='setup',
            unique_together={('account', 'contract')},
        ),
    ]
