# Generated by Django 5.1.3 on 2024-12-01 20:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpetual', '0002_rename_paid_rebate_trade_received_rebate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='liquidation_price',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
        migrations.AddField(
            model_name='position',
            name='margin_amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
    ]
