# Generated by Django 5.1.3 on 2024-12-02 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpetual', '0003_position_liquidation_price_position_margin_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perpetualwallet',
            old_name='balance',
            new_name='free',
        ),
    ]
