# Generated by Django 5.1.3 on 2024-12-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpetual', '0004_rename_balance_perpetualwallet_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='match_tag',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
