# Generated by Django 5.1.3 on 2024-12-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpetual', '0007_remove_order_locked_amount_remove_order_locked_asset_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='close_only',
            new_name='reduce_only',
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, choices=[('limit', 'limit'), ('market', 'market')], default='limit', max_length=20, null=True),
        ),
    ]
