# Generated by Django 5.1.3 on 2025-01-06 20:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpetual', '0010_alter_orderlock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='hard_liquidation_price',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
    ]
