# Generated by Django 5.1.3 on 2025-01-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpetual', '0011_position_hard_liquidation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='liquidation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
