# Generated by Django 5.1.3 on 2025-01-24 09:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpetual', '0014_position_pnl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='pnl',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.0'), max_digits=18, null=True),
        ),
    ]
